### ISSUE TITLE
node_modules should be removed from the repository and included in .gitignore

### ISSUE THREAD

**Issue by rmtsukuru** [CWDG/design-circle-old#5]
Make sure node_modules is ignored by Git and is no longer included in the repository.

**Comment by J3RN** [comment]
Thanks for reporting this issue, I'll try to get to it later today.

**Comment by btmills** [comment]
While this is true for libraries which themselves are installed via npm, for anything that gets deployed, such as a website, [dependencies should be checked in](http://www.futurealoof.com/posts/nodemodules-in-git.html).

**Comment by J3RN** [comment]
@btmills I trust your judgement here. However, while looking for a good `.gitignore` I came across a single line that most everyone insisted upon, `/node_modules/**/node_modules/`, which seems to imply recursive nesting. What are your thoughts?

**Comment by btmills** [comment]
I'd never heard of ignoring transitive dependencies before, so I've done some research, and I still don't think it's a good idea. For reference, see the [npm website's own `.gitignore`](https://github.com/npm/npm-www/blob/master/.gitignore). They only ignore certain dependencies, but most get checked in.

**Comment by J3RN** [comment]
I’d be happy to keep them, but it’s causing problems for our Windows 8 users. What happened to Microsoft paying to work with Joyent? Anyhow, there’s a closed issue on Node, which you can find [here](https://github.com/joyent/node/issues/6960). I’m pretty sure that their solution was “Not actually our problem.”

**Comment by btmills** [comment]
What sort of problems are they seeing? We should be ignoring `node_modules/.bin` for sure, since that just contains compiled binaries, which are indeed system-dependent. I believe the flow should go something like this:
1. First clone brings down all source code, including dependencies
2. `npm install` compiles binary dependencies from source
3. Code, commit, push as usual, with changes to `node_modules/.bin` ignored
4. Pull new code, no need to `npm install` because dependencies didn't change
5. Pull a dependency upgrade and `npm install` to recompile
